### ISSUE TITLE
Ctrl+V paste is not working in VNC web interface

### ISSUE THREAD

**Issue by AlexeiScherbakov** [jlesage/docker-jdownloader-2#104]
Tight VNC Viewer is working as expected, but in web interface paste feature is not working

**Comment by jlesage** [comment]
How do you reproduce ?
I tried on Safari, Chrome and Firefox and pasting via ctrl+v is working for me.

**Comment by AlexeiScherbakov** [comment]
May be it because I use it on Raspberry Pi?
I use ```daniel0076/jdownloader-2:aarch64-v0.1```

**Comment by jlesage** [comment]
Ah, it seems that you created the issue on the wrong repo :) 

This repo is for the jlesage/jdownloader-2 Docker image.

**Comment by r2ixuz** [comment]
I am on MacOS Moneterey and paste does not work for me. Tested with Chrome and CONTROL+V and COMMAND+V. Double pressing this combinations does also not work. Pasting via VNC client works.

**Comment by danilevy1212** [comment]
Same situation as @r2ixuz, running raspberry pi.

**Comment by Slomo17** [comment]
Same for me with Firefox, running it on an x64 server with docker

**Comment by jlesage** [comment]
This should now be fixed with the latest image.

**Comment by r2ixuz** [comment]
Unfortunately doesn't fix it for me. Exactly the same behaviour as before.

**Comment by jlesage** [comment]
Can you provide the output of `docker inspect <container name>` ?
